AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
      - shared
Resources:

    VariablesReportLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            FunctionName: "variables-report"
            Description: "Variables Report Lambda Function"
            Environment:
                Variables:
                    CORE_VARIABLES_UPLOAD_PATH: "variables-explorer/core_variables_data_model.json"
                    VARIABLE_REPORT_PATH: "variables-explorer/Complete-Data-Variable-Report.xlsx"
                    BUCKET: "datahub.stanford.edu"
                    ALL_VARS_UPLOAD_PATH: "variables-explorer/all_variables_data_model.json"
                    SECRET_NAME: "application_prod"
                    REPORT_NAME: "Complete-Data-Variable-Report.xlsx"
                    TEMPLATE_REPORT_PATH: "variables-report/Template Variable Report.xlsx"
                    REGION: !Ref AWS::Region

            Handler: "lambda_function.lambda_handler"
            Architectures:
              - "x86_64"
            Code:
                ZipFile: |
                    import json
                    def lambda_handler(event, context):
                        return {
                            'statusCode': 200,
                            'body': json.dumps('Hello from Variables Report Lambda!')
                        }
            MemorySize: 512
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole"
            Runtime: "python3.11"
            Timeout: 60
            TracingConfig:
                Mode: "PassThrough"
            VpcConfig:
                SubnetIds:
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ1"
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ2"
                SecurityGroupIds:
                  - Fn::ImportValue: !Sub "DataHub-ECS-${Environment}-Lambda-SecurityGroup"
            # Layers:
            #   - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:psycopg2-custom:1"
            #   - !Sub "arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python311:16"
            EphemeralStorage:
                Size: 512

    DataHubReporterTestLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: "DataHub Reporter Test Lambda Function"
            FunctionName: "datahub-reporter-test"
            Architectures:
              - "x86_64"
            Code:
                ZipFile: |
                    import json
                    def lambda_handler(event, context):
                        return {
                            'statusCode': 200,
                            'body': json.dumps('Hello from DataHub Reporter Test!')
                        }
            MemorySize: 1024
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole"
            Timeout: 60
            Runtime: "python3.11"
            TracingConfig:
                Mode: "PassThrough"
            VpcConfig:
                SubnetIds:
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ1"
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ2"
                SecurityGroupIds:
                  - Fn::ImportValue: !Sub "DataHub-ECS-${Environment}-Lambda-SecurityGroup"
            EphemeralStorage:
                Size: 512

    DataHubEmailServiceLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: "DataHub Email Service Lambda Function"
            Environment:
                Variables:
                    SPRING_PROFILES_ACTIVE: "test"
            FunctionName: "DataHub-EmailService"
            Handler: "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest"
            Architectures:
              - "x86_64"
            Code:
                ZipFile: |
                    import json
                    def lambda_handler(event, context):
                        return {
                            'statusCode': 200,
                            'body': json.dumps('Hello from DataHub Email Service!')
                        }
            MemorySize: 2048
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/ses-sqs-lambda-role-cme1rbbm"
            Runtime: "java17"
            Timeout: 60
            TracingConfig:
                Mode: "PassThrough"
            VpcConfig:
                SubnetIds:
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ1"
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ2"
                SecurityGroupIds:
                  - Fn::ImportValue: !Sub "DataHub-ECS-${Environment}-Lambda-SecurityGroup"
            EphemeralStorage:
                Size: 512

    DataHubOpenSearchRefreshLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            Environment:
                Variables:
                    REGION_NAME: "us-east-1"
                    SECRET_NAME: "application_prod"
                    ALIAS_NAME: "study_search"
                    INDEX_NAME: "study_v101"
            FunctionName: "DataHub-OpenSearchRefresh"
            Architectures:
              - "arm64"
            Code:
                ZipFile: |
                    import json
                    def lambda_handler(event, context):
                        return {
                            'statusCode': 200,
                            'body': json.dumps('Hello from OpenSearch Refresh!')
                        }
            MemorySize: 1024
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole"
            Timeout: 900
            TracingConfig:
                Mode: "PassThrough"
            VpcConfig:
                SubnetIds:
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ1"
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ2"
                SecurityGroupIds:
                  - Fn::ImportValue: !Sub "DataHub-ECS-${Environment}-Lambda-SecurityGroup"
            EphemeralStorage:
                Size: 512

    DataHubPublicationScriptLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: "DataHub-PublicationScript"
            Architectures:
              - "x86_64"
            Code:
                ZipFile: |
                    import json
                    def lambda_handler(event, context):
                        return {
                            'statusCode': 200,
                            'body': json.dumps('Hello from Publication Script!')
                        }
            MemorySize: 128
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole"
            Timeout: 60
            TracingConfig:
                Mode: "PassThrough"
            VpcConfig:
                SubnetIds:
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ1"
                  - Fn::ImportValue: !Sub "DataHub-Networking-${Environment}-Private-Subnet-AZ2"
                SecurityGroupIds:
                  - Fn::ImportValue: !Sub "DataHub-ECS-${Environment}-Lambda-SecurityGroup"
            EphemeralStorage:
                Size: 512

    VariablesReportLambdaPermission:
        Type: "AWS::Lambda::Permission"
        Properties:
            Action: "lambda:InvokeFunction"
            FunctionName: !GetAtt VariablesReportLambda.Arn
            Principal: "events.amazonaws.com"
            SourceArn: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/VARIABLES-REPORT"

    # PsycoPG2CustomLayer:
    #     Type: "AWS::Lambda::LayerVersion"
    #     Properties:
    #         Description: "Python 3.11 psycopg2 layer - https://stackoverflow.com/questions/71493439/unable-to-import-module-lambda-function-no-module-named-psycopg2-psycopg-aw/77012246#7701224"
    #         CompatibleRuntimes:
    #           - "python3.11"
    #         LayerName: "psycopg2-custom"
    #         Content:
    #             S3Bucket: "prod-iad-c1-djusa-layers"
    #             S3Key: !Sub "/snapshots/${AWS::AccountId}/psycopg2-custom-abce5ae8-3c12-4862-aef1-414d9c11c7ee"

    # EmailServiceSQSEventSourceMapping:
    #     Type: "AWS::Lambda::EventSourceMapping"
    #     Properties:
    #         BatchSize: 10
    #         EventSourceArn: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:testEmailQueue"
    #         FunctionName: !GetAtt DataHubEmailServiceLambda.Arn
    #         Enabled: true
    #         MaximumBatchingWindowInSeconds: 0

Outputs:
  VariablesReportLambdaArn:
    Description: "Variables Report Lambda ARN"
    Value: !GetAtt VariablesReportLambda.Arn
    Export:
      Name: !Sub "DataHub-Lambda-${Environment}-VariablesReportLambda-Arn"

  DataHubReporterTestLambdaArn:
    Description: "DataHub Reporter Test Lambda ARN"
    Value: !GetAtt DataHubReporterTestLambda.Arn
    Export:
      Name: !Sub "DataHub-Lambda-${Environment}-DataHubReporterTestLambda-Arn"

  DataHubEmailServiceLambdaArn:
    Description: "DataHub Email Service Lambda ARN"
    Value: !GetAtt DataHubEmailServiceLambda.Arn
    Export:
      Name: !Sub "DataHub-Lambda-${Environment}-DataHubEmailServiceLambda-Arn"

  DataHubOpenSearchRefreshLambdaArn:
    Description: "DataHub OpenSearch Refresh Lambda ARN"
    Value: !GetAtt DataHubOpenSearchRefreshLambda.Arn
    Export:
      Name: !Sub "DataHub-Lambda-${Environment}-DataHubOpenSearchRefreshLambda-Arn"

  DataHubPublicationScriptLambdaArn:
    Description: "DataHub Publication Script Lambda ARN"
    Value: !GetAtt DataHubPublicationScriptLambda.Arn
    Export:
      Name: !Sub "DataHub-Lambda-${Environment}-DataHubPublicationScriptLambda-Arn"
