AWSTemplateFormatVersion: "2010-09-09"
Description: >-
    Last Modified: 2025/10/16 17:06:37
    "DataHub Networking stack"

Parameters:
  Environment:
    Type: String
    Description: The Project Environment
    AllowedValues:
      - dev
      - test
      - prod
      - shared
  ProjectName:
    Type: String
    Description: The Project name
    Default: datahub
    AllowedValues:
      - datahub

Conditions:
  DEV: !Equals [!Ref Environment, dev]
  TEST: !Equals [!Ref Environment, test]
  PROD: !Equals [!Ref Environment, prod]
  NOTDEV: !Not [!Equals [!Ref Environment, dev]]
  NOTPROD: !Not [!Equals [!Ref Environment, prod]]

Resources:
  DataHubVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.40.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: "default"
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-${Environment}"

  DataHubPublicSubnetAZ2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !GetAtt DataHubPrivateSubnetAZ2.AvailabilityZone
      CidrBlock: "10.40.32.0/20"
      VpcId: !Ref DataHubVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-Public-Subnet-AZ2-${Environment}"

  DataHubPublicSubnetAZ1:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !GetAtt DataHubPrivateSubnetAZ1.AvailabilityZone
      CidrBlock: "10.40.16.0/20"
      VpcId: !Ref DataHubVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-Public-Subnet-AZ1-${Environment}"

  DataHubPrivateSubnetAZ1:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: "10.40.48.0/20"
      VpcId: !Ref DataHubVPC
      MapPublicIpOnLaunch: false
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-Private-SubnetAZ1-${Environment}"

  DataHubPrivateSubnetAZ2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: "10.40.64.0/20"
      VpcId: !Ref DataHubVPC
      MapPublicIpOnLaunch: false
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-Private-Subnet-AZ2-${Environment}"

  DataHubInternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: "Name"
          Value: !Sub "${ProjectName}-Internet-Gateway-${Environment}"
        - Key: "Environment"
          Value: !Sub "${Environment}"

  DataHubPrivateRoutesAZ1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref DataHubVPC
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-Private-Routes-AZ1-${Environment}"

  DataHubPrivateRoutesAZ2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref DataHubVPC
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-Private-Routes-AZ2-${Environment}"

  DataHubPublicRoutesAZ1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref DataHubVPC
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-Public-Routes-${Environment}"

  DataHubPublicRoutesAZ2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref DataHubVPC
      Tags:
        - Key: "Environment"
          Value: !Sub "${Environment}"
        - Key: "Name"
          Value: !Sub "${ProjectName}-Public-Routes2-${Environment}"

  EC2Route2:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref EC2NatGateway
      RouteTableId: !Ref DataHubPrivateRoutesAZ1

  EC2Route3:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref DataHubInternetGateway
      RouteTableId: !Ref DataHubPublicRoutesAZ1

  NatGateway1EIP:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc

  EC2NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
        AllocationId: !GetAtt NatGateway1EIP.AllocationId
        SubnetId: !Ref DataHubPublicSubnetAZ1
        Tags:
          -
            Key: "Environment"
            Value: !Sub "${Environment}"
          -
            Key: "Name"
            Value: !Sub "${ProjectName}-Nat-Gateway-${Environment}"


# RDS PROXY ENDPOINT
  # DataHubVPCEndpoint:
  #   Type: "AWS::EC2::VPCEndpoint"
  #   Properties:
  #     VpcEndpointType: "Interface"
  #     VpcId: !Ref DataHubVPC
  #     ServiceName: !Sub "com.amazonaws.vpce.${AWS::Region}.vpce-svc-045553b17ec91b500"
  #     PolicyDocument: |
  #         {
  #           "Statement": [
  #             {
  #               "Action": "*",
  #               "Effect": "Allow",
  #               "Principal": "*",
  #               "Resource": "*"
  #             }
  #           ]
  #         }
  #     SubnetIds:
  #       - !Ref DataHubPublicSubnetAZ1
  #       - !Ref DataHubPrivateSubnetAZ1
  #     PrivateDnsEnabled: false
  #     SecurityGroupIds:
  #       - !Ref ECSHostSecurityGroup

  DataHubS3VPCEndpoint:
      Type: "AWS::EC2::VPCEndpoint"
      Properties:
          VpcEndpointType: "Interface"
          VpcId: !Ref DataHubVPC
          ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
          PolicyDocument: |
              {
                "Statement": [
                  {
                    "Action": "*", 
                    "Effect": "Allow", 
                    "Principal": "*", 
                    "Resource": "*"
                  }
                ]
              }
          SubnetIds:
            - !Ref DataHubPrivateSubnetAZ1
            - !Ref DataHubPrivateSubnetAZ2
          PrivateDnsEnabled: false
          SecurityGroupIds:
            - !Ref ECSHostSecurityGroup

  # DataHubVPCEndpoint3:
  #   Type: "AWS::EC2::VPCEndpoint"
  #   Properties:
  #     VpcEndpointType: "Interface"
  #     VpcId: !Ref DataHubVPC
  #     ServiceName: !Sub "com.amazonaws.${AWS::Region}.datasync"
  #     PolicyDocument: |
  #         {
  #           "Statement": [
  #             {
  #               "Action": "*",
  #               "Effect": "Allow",
  #               "Principal": "*",
  #               "Resource": "*"
  #             }
  #           ]
  #         }
  #     SubnetIds:
  #       - !Ref DataHubPrivateSubnetAZ1
  #       - !Ref DataHubPrivateSubnetAZ2
  #     PrivateDnsEnabled: true
  #     SecurityGroupIds:
  #       - "sg-0aa8e3f5049fbe1bf"

  DataHubVPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref DataHubInternetGateway
      VpcId: !Ref DataHubVPC

  EC2SubnetRouteTableAssociation:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        RouteTableId: !Ref DataHubPrivateRoutesAZ1
        SubnetId: !Ref DataHubPrivateSubnetAZ1

  EC2SubnetRouteTableAssociation2:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref DataHubPrivateRoutesAZ2
      SubnetId: !Ref  DataHubPrivateSubnetAZ2

  EC2SubnetRouteTableAssociation3:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
        RouteTableId: !Ref DataHubPublicRoutesAZ1
        SubnetId: !Ref DataHubPublicSubnetAZ1

  EC2SubnetRouteTableAssociation4:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref DataHubPublicRoutesAZ2
      SubnetId: !Ref DataHubPublicSubnetAZ2

  ECSHostSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          VpcId: !Ref DataHubVPC
          GroupDescription: Access to the ECS hosts and the tasks/containers that run on them
          SecurityGroupIngress:
              # Only allow inbound access to ECS from the ELB
              - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
                IpProtocol: -1
              - CidrIp: 10.40.0.0/16
                IpProtocol: -1
          Tags:
              - Key: Name
                Value: !Sub "${ProjectName}-ECS-Hosts-${Environment}"

  # This security group defines who/where is allowed to access the Application Load Balancer.
  # By default, we've opened this up to the public internet (0.0.0.0/0) but can you restrict
  # it further if you want.
  LoadBalancerSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          VpcId: !Ref DataHubVPC
          GroupDescription: Access to the load balancer that sits in front of ECS
          SecurityGroupIngress:
              # Allow access from anywhere to our ECS services
              - CidrIp: 10.40.0.0/16
                IpProtocol: -1
          Tags:
              - Key: Name
                Value: !Sub "${ProjectName}-LoadBalancers-${Environment}"

Outputs:
  VpcId:
    Value: !Ref DataHubVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPC-ID"

  PublicSubnetAZ1:
    Value: !Ref DataHubPublicSubnetAZ1
    Export:
      Name: !Sub "${AWS::StackName}-Public-Subnet-AZ1"

  PublicSubnetAZ2:
    Value: !Ref DataHubPublicSubnetAZ2
    Export:
      Name: !Sub "${AWS::StackName}-Public-Subnet-AZ2"

  PrivateSubnetAZ1:
    Value: !Ref DataHubPrivateSubnetAZ1
    Export:
      Name: !Sub "${AWS::StackName}-Private-Subnet-AZ1"

  PrivateSubnetAZ2:
    Value: !Ref DataHubPrivateSubnetAZ2
    Export:
      Name: !Sub "${AWS::StackName}-Private-Subnet-AZ2"

  LoadBalancerSecurityGroup:
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancer-SecurityGroup"

  ECSHostSecurityGroup:
    Value: !Ref ECSHostSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-ECS-Host-SecurityGroup"
