AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Last Modified: 2026/01/20 14:30:00
  "S3 Buckets stack - Bucket names must be globally unique"
Parameters:
  Environment:
    Type: String
    Description: The Project Environment
    AllowedValues:
      - dev
      - test
      - staging
      - prod
      - shared
  ProjectName:
    Type: String
    Description: The Project name (must be lowercase for S3 bucket names; e.g. redwood not Redwood)
    Default: canopy
  DeploymentId:
    Type: String
    Description: A unique identifier to ensure S3 bucket names are globally unique (must be lowercase for S3 bucket names)

Conditions:
  DEV: !Equals [!Ref Environment, dev]
  TEST: !Equals [!Ref Environment, test]
  PROD: !Equals [!Ref Environment, prod]
  NOTDEV: !Not [!Equals [!Ref Environment, dev]]
  NOTPROD: !Not [!Equals [!Ref Environment, prod]]

Resources:
  ## Required by application
  S3BucketCanopyUploadPortal:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete ## CHANGE THIS
    Properties:
      BucketName: !Sub "${ProjectName}-upload-portal-${DeploymentId}-${Environment}"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"

  ## Required by SFTP server for user home directories
  S3BucketSftpCanopy:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete ## CHANGE THIS
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub "${ProjectName}-sftp-${DeploymentId}-${Environment}"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: false
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      Tags:
      - Value: "SFTP"
        Key: "Name"

  ## Required by Submission for in-review files for PII processing
  S3BucketCanopyReview:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete ## CHANGE THIS
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub "${ProjectName}-review-${DeploymentId}-${Environment}"
      VersioningConfiguration:
        Status: "Enabled"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"

## Resource bucket for study UUID spreadsheet, and other static resources
  S3BucketCanopyResources:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete ## CHANGE THIS
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub "${ProjectName}-resources-${DeploymentId}-${Environment}"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      Tags:
      - Key: "Environment"
        Value: !Sub "${Environment}"

## Bucket containing approved files for access after PII processing
  S3BucketCanopyDefault:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete ## CHANGE THIS
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub "${ProjectName}-default-${DeploymentId}-${Environment}"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"

  ## Bucket containing Lambda function code artifacts for deployment
  S3BucketCanopyLambdaArtifacts:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete ## CHANGE THIS
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Sub "${ProjectName}-lambda-artifacts-${DeploymentId}-${Environment}"
      Tags:
      - Key: "Environment"
        Value: !Sub "${Environment}"
      VersioningConfiguration:
        Status: "Enabled"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"

Outputs:
  S3BucketCanopyReviewName:
    Description: "The ARN of the S3 bucket for review files"
    Value: !GetAtt S3BucketCanopyReview.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketCanopyReview-Arn"
  S3BucketCanopyDefaultName:
    Description: "The ARN of the S3 bucket for default files"
    Value: !GetAtt S3BucketCanopyDefault.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketCanopyDefault-Arn"
  S3BucketSftpCanopyName:
    Description: "The ARN of the S3 bucket for SFTP user home directories"
    Value: !GetAtt S3BucketSftpCanopy.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketSftpCanopy-Arn"
  S3BucketCanopyUploadPortalName:
    Description: "The ARN of the main S3 bucket for the Upload Portal"
    Value: !GetAtt S3BucketCanopyUploadPortal.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketCanopyUploadPortal-Arn"
  S3BucketCanopyLambdaArtifactsName:
    Description: "The ARN of the S3 bucket for Lambda function artifacts"
    Value: !GetAtt S3BucketCanopyLambdaArtifacts.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketCanopyLambdaArtifacts-Arn"
  S3BucketCanopyResourcesName:
    Description: "The ARN of the S3 bucket for static resources (study UUID spreadsheet, variable reports, etc.)"
    Value: !GetAtt S3BucketCanopyResources.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketCanopyResources-Arn"
