AWSTemplateFormatVersion: "2010-09-09"
Description: >-
    Last Modified: 2025/11/07 14:43:07
    "RADx SageMaker stack"
    
Parameters:
  Environment:
    Type: String
    Description: The Project Environment
    AllowedValues:
      - dev
      - test
      - prod
      - shared
  ProjectName:
    Type: String
    Description: The Project name
    Default: radx
    AllowedValues:
      - radx
Resources:

    SageMakerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId:
              Fn::ImportValue: !Sub "RADx-Networking-${Environment}-VPC-ID"
            GroupDescription: Security Group for the SageMaker Environment
            SecurityGroupIngress:
                # Allow access from anywhere to SageMaker
                - CidrIp: 0.0.0.0/0
                  IpProtocol: -1
            Tags: 
                - Key: Name
                  Value: !Sub "${ProjectName}-SageMaker-${Environment}"

    SageMakerDomain:
        Type: "AWS::SageMaker::Domain"
        Properties:
            DomainName: !Sub "${ProjectName}-sagemaker-domain-${Environment}"
            AuthMode: "IAM"
            VpcId:
              Fn::ImportValue: !Sub "RADx-Networking-${Environment}-VPC-ID"
            AppNetworkAccessType: "VpcOnly"
            SubnetIds: 
                - Fn::ImportValue: !Sub "RADx-Networking-${Environment}-Private-Subnet-AZ1"
                - Fn::ImportValue: !Sub "RADx-Networking-${Environment}-Private-Subnet-AZ2"
            DefaultUserSettings: 
                ExecutionRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/SagemakerExecutionRole"
                SecurityGroups: 
                  - !Ref SageMakerSecurityGroup
                KernelGatewayAppSettings: {}
                RSessionAppSettings: {}
                # SharingSettings: 
                #     NotebookOutputOption: "Allowed"
                #     S3OutputPath: "s3://sagemaker-studio-aex13x9gewl/sharing"
                # JupyterServerAppSettings: 
                #     DefaultResourceSpec: 
                #         SageMakerImageArn: !Sub "arn:aws:sagemaker:${AWS::Region}:236514542706:image/jupyter-server-3"
                #         InstanceType: "system"
                # CanvasAppSettings: 
                #     TimeSeriesForecastingSettings: 
                #         Status: "DISABLED"
                #     ModelRegisterSettings: 
                #         Status: "DISABLED"
                #     WorkspaceSettings: 
                #         S3ArtifactPath: !Sub "s3://sagemaker-${AWS::Region}-${AWS::AccountId}"
                #     KendraSettings: 
                #         Status: "DISABLED"
                #     DirectDeploySettings: 
                #         Status: "DISABLED"
                # JupyterLabAppSettings: 
                #     DefaultResourceSpec: 
                #         LifecycleConfigArn: !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:studio-lifecycle-config/jupyter-launch-update-v2"
                #     LifecycleConfigArns: 
                #       - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:studio-lifecycle-config/jupyter-launch-update"
                #       - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:studio-lifecycle-config/jupyter-launch-update"
                #       - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:studio-lifecycle-config/jupyter-launch-update-v2"
                CodeEditorAppSettings: {}
                SpaceStorageSettings: 
                    DefaultEbsStorageSettings: 
                        DefaultEbsVolumeSizeInGb: 5
                        MaximumEbsVolumeSizeInGb: 100
                DefaultLandingUri: "studio::"
                StudioWebPortal: "ENABLED"

    SageMakerAppImageConfig:
        Type: "AWS::SageMaker::AppImageConfig"
        Properties:
            AppImageConfigName: !Sub "${ProjectName}-app-image-config"
            KernelGatewayImageConfig: 
                KernelSpecs: 
                  - 
                    Name: "Python 3"
                    DisplayName: "Python 3"
                FileSystemConfig: 
                    MountPath: "/home/sagemaker-user"
                    DefaultUid: 1000
                    DefaultGid: 100