AWSTemplateFormatVersion: "2010-09-09"
Description: >-
    Last Modified: 2025/10/16 17:06:37
    "RADx Secrets Manager stack"

Parameters:
  Environment:
    Type: String
    Description: The Project Environment
    AllowedValues:
      - dev
      - test
      - prod
      - shared
  ProjectName:
    Type: String
    Description: The Project name
    Default: radx
    AllowedValues:
      - radx

Conditions: 
  DEV: !Equals [!Ref Environment, dev]
  TEST: !Equals [!Ref Environment, test]
  PROD: !Equals [!Ref Environment, prod] 
  NOTDEV: !Not [!Equals [!Ref Environment, dev]]
  NOTPROD: !Not [!Equals [!Ref Environment, prod]]


Resources:

    RDSMasterSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: "rds/postgresql/prod"
            Description: !Sub "Secret associated with primary RDS DB instance: arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:radx-prod-postgresql"
            SecretString: '{"username":"postgres","password":"REPLACEME"}'

    RDSAdminSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: "rds/radx_admin/prod"
            Description: "Access to production credentials"
            SecretString: '{"username":"radx_admin","password":"REPLACEME"}'

    RDSUserSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: "rds/radx_user/prod"
            SecretString: '{"username":"radx_user","password":"REPLACEME"}'

    ApplicationSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: 
                !Sub  "application_${Environment}"
            Description: !Sub "Secret associated with primary RDS DB instance: arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:radx-prod-postgresql"
            SecretString: '{
                "dbuser":"radx_user",
                "password":"REPLACEME",
                "engine":"postgres",
                "host":"radx-prod-db-proxy.proxy-c8fktbj4v0a9.us-west-2.rds.amazonaws.com", ## RDS Proxy Endpoint
                "port":"5432",
                "dbname":"RADx_prod",
                "dbInstanceIdentifier":"radx-prod-postgresql",
                "opensearch.hostname":"vpc-radx-os-prod-lxosg4cegzozq2pbj2o6i3kbp4.us-west-2.es.amazonaws.com", ## OpenSearch Endpoint
                "opensearch.port":"443",
                "opensearch.scheme":"https",
                "opensearch.username":"opensearch",
                "opensearch.password":"REPLACEME",
                "supportEmail":"RADx-DataHub@nih.gov", ## Support Email
                "gmailPassword":"Not Applicable",
                "rasclientid":"a16bee84-0175-406e-ae96-193920f9aada", ## RAS Client ID
                "rasclientsecret":"4cf18242-6965-4eeb-83cf-f7e810d80b4f", ## RAS Client Secret
                "redirecturl":"https://radxdatahub.nih.gov/api/user/v1/ras", ## Redirect URL
                "GA1PropertyId":"341918636", ## GA1 Property ID
                "GACredentials": "{\"type\": \"service_account\",\"project_id\": \"radx-datahub-ga4\",\"private_key_id\": \"REPLACEME\",\"private_key\": \"REPLACEME\\n\",\"client_email\": \"analytics-prod@radx-datahub-ga4.iam.gserviceaccount.com\",\"client_id\": \"REPLACEME\",\"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\"token_uri\": \"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/analytics-prod@radx-datahub-ga4.iam.gserviceaccount.com\",\"universe_domain\": \"googleapis.com\"}",
                "EmailQueue":"prodEmailQueue",
                "rasurl":"https://sts.nih.gov",
                "InReviewS3Bucket":"covid-radx-review",
                "ApprovedS3Bucket":"covid-radx-default",
                "MtaFormBucket":"prod-covid-radx-ingest-pdf",
                "PiiQueue":"pii-sqs-queue-prod",
                "SFTPQueue":"sftp-queue-prod",
                "SFTPIngestBucket":"sftp-radx",
                "HostURL":"https://radxdatahub.nih.gov",
                "StakeholderEmailsWorkbenchSubmit":"Mistry_Nilesh@bah.com,Luker_Emma@bah.com,fujimoto_alissa@bah.com",
                "StakeholderEmailsStudyReg":"",
                "VariablesPagePath":"radxdatahub.nih.gov/variables-explorer/Variables-Page.xlsx",
                "VariablesReportPath":"radxdatahub.nih.gov/variables-explorer/Complete-Data-Variable-Report.xlsx",
                "UuidSpreadsheetPath":"radxdatahub.nih.gov/radx-s3-resources/RADx-Data-Hub_Study-IDs.xlsx",
                "DataCiteUrl":"https://api.datacite.org/dois","DataCiteUser":"NIHOD.RADX",
                "DataCitePassword":"Mullets9Axes5anatomy",
                "DataCitePrefix":"10.60773",
                "accountId":"652837727789",
                "rasauth":"https://sts.nih.gov/auth/oauth/v2/authorize?client_id=a16bee84-0175-406e-ae96-193920f9aada&prompt=login+consent&redirect_uri=https://radxdatahub.nih.gov/api/user/v1/ras&response_type=code&scope=openid+email+profile+ga4gh_passport_v1+department",
                "StakeholderEmailsWorkbenchAction":"Schweikert_Joseph@bah.com,Mistry_Nilesh@bah.com,Luker_Emma@bah.com",
                "apikey":"202dc5b4-13b1-4b16-b657-73f03ce878d9",
                "ResourceBucket":"radxdatahub.nih.gov",
                "WeeklyReportPath":"radx-s3-resources/RADx-DataHub-Weekly-Metrics.csv",
                "WeeklyReportFileName":"RADx-DataHub-Weekly-Metrics.csv",
                "UploadPortalBucket":"radx-upload-portal-prod"
                }'
