AWSTemplateFormatVersion: "2010-09-09"
Description: >-
    Last Modified: 2025/10/16 17:06:37
    "DataHub Secrets Manager stack"

Parameters:
  Environment:
    Type: String
    Description: The Project Environment
    AllowedValues:
      - dev
      - test
      - prod
      - shared
  ProjectName:
    Type: String
    Description: The Project name
    Default: datahub
    AllowedValues:
      - datahub

Conditions:
  DEV: !Equals [!Ref Environment, dev]
  TEST: !Equals [!Ref Environment, test]
  PROD: !Equals [!Ref Environment, prod]
  NOTDEV: !Not [!Equals [!Ref Environment, dev]]
  NOTPROD: !Not [!Equals [!Ref Environment, prod]]


Resources:

    RDSMasterSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: "rds/postgresql/prod"
            Description: !Sub "Secret associated with primary RDS DB instance: arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:datahub-prod-postgresql"
            SecretString: '{"username":"postgres","password":"REPLACEME"}'

    RDSAdminSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: "rds/datahub_admin/prod"
            Description: "Access to production credentials"
            SecretString: '{"username":"datahub_admin","password":"REPLACEME"}'

    RDSUserSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: "rds/datahub_user/prod"
            SecretString: '{"username":"datahub_user","password":"REPLACEME"}'

    ApplicationSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name:
                !Sub  "application_${Environment}"
            Description: !Sub "Secret associated with primary RDS DB instance: arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:datahub-prod-postgresql"
            SecretString: '{
                "dbuser":"datahubpostgresdev",
                "password":"REPLACEME", 
                "engine":"postgres",
                "host":"datahub-postgresql-dev.cyhmos66o8v8.us-east-1.rds.amazonaws.com",
                "port":"5432",
                "dbname":"datahub_dev",
                "dbDriverClassName":"org.postgresql.Driver",
                "spring_profiles_active":"dev",
                "SEARCH_HOST":"https://vpc-datahub-opensearch-dev-a6di5egb7vext6gidgieaxbsuu.us-east-1.es.amazonaws.com", 
                "SEARCH_USERNAME":"datahub_admin",
                "SEARCH_PASSWORD":"REPLACEME",
                "HostURL":"http://datahub-dev-1822128394.us-east-1.elb.amazonaws.com",
                "supportEmail":"ycao77@stanford.edu", 
                "gmailPassword":"Not Applicable",
                "rasurl":"https://sts.nih.gov",
                "rasclientid":"a16bee84-0175-406e-ae96-193920f9aada", 
                "rasclientsecret":"4cf18242-6965-4eeb-83cf-f7e810d80b4f", 
                "rasauth":"https://auth.nih.gov/auth/authorize",
                "redirecturl":"https://datahub.stanford.edu/api/user/v1/ras", 
                "GA1PropertyId":"CHANGEME", 
                "GACredentials": "{\"type\": \"service_account\",\"project_id\": \"datahub-ga4\",\"private_key_id\": \"REPLACEME\",\"private_key\": \"REPLACEME\\n\",\"client_email\": \"analytics-prod@datahub-ga4.iam.gserviceaccount.com\",\"client_id\": \"REPLACEME\",\"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\"token_uri\": \"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/analytics-prod@datahub-ga4.iam.gserviceaccount.com\",\"universe_domain\": \"googleapis.com\"}",
                "EmailQueue":"datahub-email-queue-dev", 
                "InReviewS3Bucket":"datahub-review-stanford-dev", 
                "ApprovedS3Bucket":"datahub-default-stanford-dev",  
                "SFTPQueue":"datahub-sftp-queue-dev",   
                "SFTPIngestBucket":"sftp-datahub-stanford-dev",                
                "StakeholderEmailsWorkbenchSubmit":"ycao77@stanford.edu,attila.egyedi@stanford.edu",
                "StakeholderEmailsStudyReg":"",
                "VariablesPagePath":"datahub.stanford.edu/variables-explorer/Variables-Page.xlsx",
                "VariablesReportPath":"datahub.stanford.edu/variables-explorer/Complete-Data-Variable-Report.xlsx",
                "UuidSpreadsheetPath":"datahub.stanford.edu/datahub-s3-resources/Data-Hub_Study-IDs.xlsx",
                "DataCiteUrl":"https://api.datacite.org/dois",
                "DataCiteUser":"CHANGEME",
                "DataCitePassword":"CHANGEME",
                "DataCitePrefix":"10.60773",
                "accountId":"652837727789",
                "rasauth":"https://sts.nih.gov/auth/oauth/v2/authorize?client_id=a16bee84-0175-406e-ae96-193920f9aada&prompt=login+consent&redirect_uri=https://datahub.stanford.edu/api/user/v1/ras&response_type=code&scope=openid+email+profile+ga4gh_passport_v1+department",
                "StakeholderEmailsWorkbenchAction":"Schweikert_Joseph@bah.com,Mistry_Nilesh@bah.com,Luker_Emma@bah.com",
                "apikey":"202dc5b4-13b1-4b16-b657-73f03ce878d9",
                "ResourceBucket":"datahub.stanford.edu", 
                "WeeklyReportPath":"datahub-s3-resources/DataHub-Weekly-Metrics.csv",
                "WeeklyReportFileName":"DataHub-Weekly-Metrics.csv",
                "UploadPortalBucket":"datahub-upload-portal-stanford-dev", 
                "DATAHUB_SPRING_MANAGEMENT_USER":"admin",
                "DATAHUB_SPRING_MANAGEMENT_PASSWORD":"Password123",
                "OpensearchRefreshLambda":"DataHub-OpenSearchRefresh",
                "PiiQueue":"datahub-pii-queue-dev",
                "MtaFormBucket":"datahub-mta-form-stanford-dev",
                "StepFunctionMachineArn":"arn:aws:iam::652837727789:role/datahub-step-function-machine-role"
                }'
