AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Last Modified: 2026/01/20 14:30:00
  "Secrets Manager stack"

Parameters:
  Environment:
    Type: String
    Description: The Project Environment
    AllowedValues:
      - dev
      - test
      - prod
      - shared
  ProjectName:
    Type: String
    Description: The Project name
    Default: datahub
  PostgresMasterUsername:
    Type: String
    Description: RDS master username
  PostgresMasterPassword:
    Type: String
    NoEcho: true
    Description: RDS master password
  DataHubAdminUsername:
    Type: String
    Description: RADx admin username
  DataHubAdminPassword:
    Type: String
    NoEcho: true
    Description: RADx admin password
  DataHubUserUsername:
    Type: String
    Description: RADx application user username
  DataHubUserPassword:
    Type: String
    NoEcho: true
    Description: RADx application user password
  OpenSearchUsername:
    Type: String
    Description: OpenSearch username
    Default: opensearch
  OpenSearchPassword:
    Type: String
    NoEcho: true
    Description: OpenSearch password
  DataHubUniqueId:
    Type: String
    Description: A unique identifier to ensure S3 bucket names are globally unique
    Default: stanford

Conditions:
  DEV: !Equals [ !Ref Environment, dev ]
  TEST: !Equals [ !Ref Environment, test ]
  PROD: !Equals [ !Ref Environment, prod ]
  NOTDEV: !Not [ !Equals [ !Ref Environment, dev ] ]
  NOTPROD: !Not [ !Equals [ !Ref Environment, prod ] ]

Resources:
    ApplicationSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: !Sub "${ProjectName}_application_${Environment}"
            Description: !Sub "Secrets associated with ${ProjectName} application"
            SecretString: !Sub |
                    {
                        "dbuser":"${DataHubUserUsername}",
                        "password":"${DataHubUserPassword}", 
                        "engine":"postgres",
                        "host":"redwood-postgresql-dev.cyhmos66o8v8.us-east-1.rds.amazonaws.com",
                        "port":"5432",
                        "dbname":"${ProjectName}_${Environment}",
                        "dbDriverClassName":"org.postgresql.Driver",
                        "spring_profiles_active":"${Environment}",
                        "SEARCH_HOST":"vpc-redwood-opensearch-dev-uzcx2cvg3nmlxe23fdedj2lsoy.us-east-1.es.amazonaws.com", 
                        "SEARCH_USERNAME":"${OpenSearchUsername}",
                        "SEARCH_PASSWORD":"${OpenSearchPassword}",
                        "HostURL":"http://redwood-dev-985841589.us-east-1.elb.amazonaws.com",
                        "supportEmail":"ycao77@stanford.edu", 
                        "rasurl":"https://sts.nih.gov",
                        "rasclientid":"a16bee84-0175-406e-ae96-193920f9aada", 
                        "rasclientsecret":"4cf18242-6965-4eeb-83cf-f7e810d80b4f", 
                        "rasauth":"https://auth.nih.gov/auth/authorize",
                        "redirecturl":"https://datahub.stanford.edu/api/user/v1/ras", 
                        "GA1PropertyId":"CHANGEME", 
                        "GACredentials": "{\"type\": \"service_account\",\"project_id\": \"datahub-ga4\",\"private_key_id\": \"REPLACEME\",\"private_key\": \"REPLACEME\\n\",\"client_email\": \"analytics-prod@datahub-ga4.iam.gserviceaccount.com\",\"client_id\": \"REPLACEME\",\"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\"token_uri\": \"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/analytics-prod@datahub-ga4.iam.gserviceaccount.com\",\"universe_domain\": \"googleapis.com\"}",
                        "EmailQueue":"${ProjectName}-email-queue-${Environment}", 
                        "InReviewS3Bucket":"${ProjectName}-review-${DataHubUniqueId}-${Environment}", 
                        "ApprovedS3Bucket":"${ProjectName}-default-${DataHubUniqueId}-${Environment}",  
                        "SFTPQueue":"${ProjectName}-sftp-queue-${Environment}",   
                        "SFTPIngestBucket":"${ProjectName}-sftp-${DataHubUniqueId}-${Environment}",                
                        "StakeholderEmailsStudyReg":"ycao77@stanford.edu",
                        "UuidSpreadsheetPath":"${ProjectName}-resources-${DataHubUniqueId}-${Environment}/datahub-s3-resources/DataHub-Study-IDs.xlsx",
                        "DataCiteUrl":"https://api.datacite.org/dois",
                        "DataCiteUser":"CHANGEME",
                        "DataCitePassword":"CHANGEME",
                        "DataCitePrefix":"10.60773",
                        "rasauth":"https://sts.nih.gov/auth/oauth/v2/authorize?client_id=a16bee84-0175-406e-ae96-193920f9aada&prompt=login+consent&redirect_uri=https://datahub.stanford.edu/api/user/v1/ras&response_type=code&scope=openid+email+profile+ga4gh_passport_v1+department",
                        "apikey":"202dc5b4-13b1-4b16-b657-73f03ce878d9",
                        "ResourceBucket":"${ProjectName}-resources-${DataHubUniqueId}-${Environment}", 
                        "WeeklyReportPath":"datahub-s3-resources/DataHub-Weekly-Metrics.csv",
                        "WeeklyReportFileName":"DataHub-Weekly-Metrics.csv",
                        "UploadPortalBucket":"${ProjectName}-upload-portal-${DataHubUniqueId}-${Environment}", 
                        "DATAHUB_SPRING_MANAGEMENT_USER":"admin",
                        "DATAHUB_SPRING_MANAGEMENT_PASSWORD":"Password123",
                        "OpensearchRefreshLambda":"${ProjectName}-OpenSearchRefresh",
                        "PiiQueue":"${ProjectName}-pii-queue-${Environment}"
                    }
